name: CI

on:
  push:
  pull_request:

env:
  IMAGE_TAG: ${{ github.sha }}
  GITOPS_REPO: khanhlinh-create/linguasphere-k8s

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show repo structure
        run: |
          pwd
          ls -la
          echo "=== backend ==="
          ls -la backend || true
          echo "=== frontend ==="
          ls -la frontend || true
          echo "=== docker ==="
          ls -la docker || true

      - name: Validate docker-compose file exists 
        run: |
          test -f docker/docker-compose.yml
          echo "docker/docker-compose.yml found."

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Run Unit Tests
        run: |
          cd backend
          npm run test:unit -- --ci --reporters=default --reporters=jest-junit
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET}}
 
      - name: Upload test coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: backend/coverage/
          retention-days: 7

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v8
        with:
          projectBaseDir: .
          args: >
            "-Dsonar.projectKey=linhphuongbae_linguasphere-devsecops"
            "-Dsonar.organization=linhphuongbae"
            "-Dsonar.sources=backend,frontend"
            "-Dsonar.tests=backend/tests"
            "-Dsonar.test.inclusions=backend/tests/**/*.test.js"
            "-Dsonar.exclusions=**/node_modules/**,backend/coverage/**"
            "-Dsonar.coverage.exclusions=frontend/**,**/*.config.js,**/server.js,backend/src/models/**,**/app.js,**/routes/**"
            "-Dsonar.javascript.lcov.reportPaths=backend/coverage/unit/lcov.info"
            "-Dsonar.branch.name=${{ github.ref_name }}"
            "-Dsonar.scm.provide=git"
            "-Dsonar.verbose=true"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
      
      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Scan Backend
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/linguasphere-backend:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/linguasphere-backend:${{ env.IMAGE_TAG }} \
            ./backend

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh
          sudo mv ./bin/grype /usr/local/bin/

      - name: Scan Backend with Grype
        run: |
          grype docker:${{ secrets.DOCKERHUB_USERNAME }}/linguasphere-backend:latest --fail-on critical
      
      - name: Push Backend image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/linguasphere-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/linguasphere-backend:${{ env.IMAGE_TAG }}

      - name: Build Frontend image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/linguasphere-frontend:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/linguasphere-frontend:${{ env.IMAGE_TAG }} \
            ./frontend
      
      - name: Scan Frontend with Grype
        run: |
          grype -c .grype.yaml docker:${{ secrets.DOCKERHUB_USERNAME }}/linguasphere-frontend:latest --fail-on critical
      
      - name: Push Frontend image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/linguasphere-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/linguasphere-frontend:${{ env.IMAGE_TAG }}

      - name: Checkout GitOps repository
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v5
        with:
          repository: ${{ env.GITOPS_REPO }}
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops
          fetch-depth: 1

      - name: Patch and push GitOps manifests
        if: ${{ github.event_name == 'push'}}
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          set -euo pipefail
          cd gitops

          sed -i -E "s|image:\s*.+/linguasphere-backend:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/linguasphere-backend:${IMAGE_TAG}|" manifests/backend/backend-deployment.yaml
          sed -i -E "s|image:\s*.+/linguasphere-frontend:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/linguasphere-frontend:${IMAGE_TAG}|" manifests/frontend/frontend-deployment.yaml

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add manifests/backend/backend-deployment.yaml manifests/frontend/frontend-deployment.yaml
          if git diff --cached --quiet; then
            echo "No manifest changes to commit"
            exit 0
          fi

          git commit -m "ci: update images to ${IMAGE_TAG}"
          git push origin main